<div class="quickview-colorbox-wrap" style="display:none">
    <div id="quickview-colorbox" class="js-quickview-modal" data-bind="scope:'modalcomponent'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
{
    ".js-quickview-modal": {
        "quickView": {
            "buttonSelector": ".js-quickview-action",
            "overlayOpacity": 0.4,
            "closeButton": true,
            "width": "90%",
            "maxWidth": "1200px"
        },
        "Magento_Ui/js/core/app": {
           "components": {
                "modalcomponent": {
                    "component": "Space48_QuickView/js/quickview-modal",
                    "template": "Space48_QuickView/quick-view"
                }
            }
        }
    }
}
</script>
