<?php /** @var Space48\QuickView\Block\Catalog\Category\View\QuickView $block */ ?>
<a href="javascript:void(0)"
    id="quick-view-<?= $block->escapeHtmlAttr(__($block->getProduct()->getId()));?>"
    data-quickview-url="<?= $block->escapeHtmlAttr(__($block->getQuickViewUrl($block->getProduct()->getId(), $block->getCurrentCategory()->getId()))); ?>"
    class="action tocart primary js-quick-view js-quickview-action"
    title="<?= $block->escapeHtmlAttr(__($block->getButtonText())); ?>"
    aria-label=""
    role="button">
    <?= escapeHtml(__($block->getButtonText())) ?>
</a>
