<?php /** @var Space48\QuickView\Block\Catalog\Category\View\QuickView $block */ ?>
<a href="javascript:void(0)"
    id="quick-view-<?php echo $block->getProduct()->getId();?>"
    data-quickview-url="http://coxandcoxm2-local.space48.com/quickview/product/view/id/18"
    class="action tocart primary js-quick-view js-quickview-action"
    title="<?php echo $block->escapeHtml(__($block->getButtonText())); ?>"
    aria-label=""
    role="button">
    <?php /* @escapeNotVerified */ echo __($block->getButtonText()) ?>
</a>
