<?php
/**
 * view.phtml
 *
 * @Date        02/2017
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      @diazwatson
 */

?>

<div class="quick-view-modal" style="top: 293px;">
    <div class="quick-view-content" id="quick-view-content">
        <div class="left qview-gal">
            <div id="slidingProduct<?php echo $block->getProduct()->getData('id'); ?>" class="qview-gal-img">
                <img src="<?php echo $block->getProduct()->getData('MainImageUrl'); ?>">
            </div>
            <ul class="qview-gal-thumbs">
                <!-- this is where the media gallery images will be -->
                <?php foreach ($block->getProduct()->getGallery() as $item) : ?>
                    <li class="left">
                        <a class="active quick-thumb" href="#"><img src="<?php echo $item->getData('Url'); ?>" width="54" height="54"></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="right qview-product-info">
            <h2 class="product-name">
                <a href="<?php echo $block->getProduct()->getData('Url'); ?>"><?php echo $block->getProduct()->getData('name'); ?></a>
            </h2>
            <p id="quick_view_code" class="quick-view-code"><?php echo __('Product Code') . ':' ?><span class="product-id"><?php echo $block->getProduct()->getData('id'); ?></span></p>
            <div class="row">
                <p class="qview-product-description" id="quick_view_desc"><?php echo $block->getProduct()->getData('description'); ?></p>
            </div>
            <div class="price-box">
                <p id="quick_view_price" class="regular-price">
                    <span class="price"><?php echo $block->getProduct()->getData('price'); ?></span>
                </p>
            </div>
            <div class="row">
                <div class="left availability in-stock"><i class="icon-font icon-font-cross"></i>
                    <span class="stock-status upper"><?php echo $block->getProduct()->getData('availability'); ?></span></div>
            </div>
            <div>
                <a href="<?php echo $block->getProduct()->getData('Url'); ?>" class="button grey-button"><?php echo __('More Info'); ?></a>
            </div>
        </div>
    </div>
    <a href="#" id="quick-view-close" class="modal-close a-center" onclick="closeModal(); return false;">X</a>
</div>