<?php /** @var Space48\QuickView\Block\Catalog\Category\View\QuickView $block */ ?>
<script type="text/x-magento-init">
{
    "*": {
        "quickView": <?php echo $block->getQuickViewJson(); ?>
    }
}
</script>
<a href="#"
   id="quick-view-<?php echo $block->getProduct()->getId();?>"
   data-product-id="<?php echo $block->getProduct()->getId();?>"
   class="action tocart primary js-modal-open"
   title="<?php echo $block->escapeHtml(__($block->getButtonText())); ?>"
   aria-label=""
   role="button">
    <span><?php /* @escapeNotVerified */ echo __($block->getButtonText()) ?></span>
</a>
